#!/bin/sh

root=$(git rev-parse --show-toplevel)

port=$(cat "$root"/control/port)
if ! [ -e "$port" ]; then
    echo "not found: $port"
    exit 1
fi

if [ "$1x" = "-dx" ]; then
    exec lxterminal -e "echo $0; sleep 30"
elif [ "$1x" != "x" ]; then
    echo "flags:"
    echo "  -h  display this help"
    echo "  -d  run in separate terminal"
    exit 0
fi

echo ":$port"
tail -f "$port"
