#!/bin/sh

root=$(git rev-parse --show-toplevel)

port=$(cat "$root"/control/port)
if ! [ -e "$port" ]; then
    echo "not found: $port"
    exit 1
fi

echo "$port > $1"
echo "$1" >> "$port"
echo -n "$port <"
sleep 1s
cat "$port"
